import assert from "node:assert/strict";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { RunJournal } from "../src/journal.js";
import { isAllowedLocalRequest, loadMemorySnapshot, memoryViewerHtml, renderMemoryMarkdown, runMemoryAction } from "../src/memory-web.js";

test("memory web loads only generated working-memory pages", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "orchbun-memory-web-"));
  await mkdir(path.join(root, "working"), { recursive: true });
  await writeFile(path.join(root, "working", "project-state.md"), "# Project state\n\n- **Safe** status\n");
  const snapshot = await loadMemorySnapshot(root);
  assert.equal(snapshot.pages.length, 5);
  assert.match(snapshot.pages[0]!.markdown, /Safe/);
  assert.equal(snapshot.pages[1]!.markdown, "No memory has been generated yet.\n");
});

test("memory web escapes memory text before rendering", () => {
  const html = renderMemoryMarkdown("<!--\nGenerated by: internal\n-->\n# <script>alert(1)</script>\n\n- **Trusted** `content`");
  assert.match(html, /&lt;script&gt;/);
  assert.doesNotMatch(html, /<script>alert/);
  assert.match(html, /<strong>Trusted<\/strong>/);
  assert.match(html, /<code>content<\/code>/);
  assert.doesNotMatch(html, /Generated by|--&gt;/);
});

test("memory web page contains accessible sections and maintenance controls", () => {
  const page = memoryViewerHtml();
  assert.match(page, /Project \| OrchBun memory 1\.0/);
  assert.match(page, /aria-live="polite"/);
  assert.match(page, /Refresh/);
  assert.match(page, /Preview sleep/);
  assert.match(page, /Publish sweep/);
  assert.match(page, /Compact accepted/);
  assert.match(page, /Project files/);
  assert.match(page, /FAVICON\.png/);
  assert.match(page, /Blocked/);
  assert.match(page, /Severity/);
  assert.match(page, /\/api\/memory/);
});

test("memory web runs the same verification action as the CLI", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "orchbun-memory-web-action-"));
  const memoryRoot = path.join(root, "memory", "agents");
  const journal = new RunJournal(memoryRoot);
  await journal.initialize();
  assert.match(await runMemoryAction("verify", journal, root), /Verification passed/);
});

test("memory web rejects non-loopback hosts and origins", () => {
  assert.equal(isAllowedLocalRequest("127.0.0.1:4312", "http://127.0.0.1:4312"), true);
  assert.equal(isAllowedLocalRequest("localhost:4312", "http://localhost:4312"), true);
  assert.equal(isAllowedLocalRequest("attacker.example", "http://attacker.example"), false);
  assert.equal(isAllowedLocalRequest("127.0.0.1:4312", "https://attacker.example"), false);
});
