import { readFile, rename, writeFile } from "node:fs/promises";
import { resolveDirectMemory, type DirectMemoryNote } from "./direct-memory.js";
import { loadRoadmap, projectMarkdownPath } from "./roadmap.js";
import { roadmapReferences } from "./sleep-memory.js";

export type RoadmapProjectionResult = "updated" | "unchanged" | "absent" | "missing";

const HEADING = "## Phase P — Product work tracked in direct notes";
const START = "<!-- orchbun:phase-p:start -->";
const END = "<!-- orchbun:phase-p:end -->";
const REGION = new RegExp(`${START}([\\s\\S]*?)${END}`);

/**
 * Ad-hoc work started outside the roadmap only exists as direct notes. This projects it back into a
 * delimited block of the roadmap so the checklist stays the single place work is tracked. The lines
 * carry no stable task id on purpose: TASK_LINE ignores them, so generated work never gates a
 * milestone approval and never competes with hand-authored steps.
 */
export async function syncRoadmapProjection(
  projectRoot: string,
  notes: DirectMemoryNote[],
  relativePath = "ROADMAP.md",
): Promise<RoadmapProjectionResult> {
  const file = projectMarkdownPath(projectRoot, relativePath);
  let current: string;
  try {
    current = await readFile(file, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return "missing";
    throw error;
  }

  const roadmap = await loadRoadmap(projectRoot, relativePath);
  const superseded = resolveDirectMemory(notes).supersededNoteIds;
  const adHoc = notes
    .filter((note) => !roadmapReferences([note.task, ...note.nextActions].join("\n"), roadmap).length)
    .sort((left, right) => right.timestamp.localeCompare(left.timestamp) || right.id.localeCompare(left.id));
  const existing = REGION.exec(current);
  if (!adHoc.length && !existing) return "absent";

  const delivered = adHoc.filter((note) => note.status !== "active" || superseded.has(note.id));
  const inProgress = adHoc.filter((note) => !delivered.includes(note));
  // A sweep moves retired notes to archive/direct, so the note backing a delivered entry stops
  // existing. The roadmap is the durable record of shipped ad-hoc work: keep what was written.
  const lines = delivered.map(itemText);
  const kept = new Set(lines);
  for (const line of retainedDelivered(existing?.[1] ?? "")) if (!kept.has(line)) { lines.push(line); kept.add(line); }
  const region = [
    START,
    "<!-- Generated by orchbun memory rebuild from direct notes with no roadmap task. Do not edit by hand. -->",
    ...section("In progress", inProgress.map(itemText), " "),
    ...section("Delivered", lines, "x"),
    END,
  ].join("\n");

  const updated = existing
    ? current.replace(REGION, () => region)
    : `${current.trimEnd()}\n\n${HEADING}\n\n${region}\n`;
  if (updated === current) return "unchanged";

  const temporary = `${file}.${process.pid}.tmp`;
  await writeFile(temporary, updated);
  await rename(temporary, file);
  return "updated";
}

function section(title: string, items: string[], mark: string): string[] {
  if (!items.length) return [];
  return ["", `### ${title}`, "", ...items.map((item) => `- [${mark}] ${item}`)];
}

function retainedDelivered(region: string): string[] {
  return region.split("\n").flatMap((line) => /^- \[x\] (.+)$/.exec(line)?.[1]?.trim() ?? []);
}

/** Keeps one note on one line and never lets its text be re-parsed as a stable roadmap task. */
export function itemText(note: DirectMemoryNote): string {
  const text = note.task.replace(/\s+/g, " ").replace(/^(?:[-*+]\s+)?(?:\[[ xX]\]\s*)?/, "").trim();
  return text.replace(/^\*\*([A-Z][A-Z0-9]*(?:-[A-Z0-9]+)+)\*\*/, "$1") || note.slug;
}
